apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 754309742701.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:0ec03a836cf61103561ec70baad8f4265fbe2a6e
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: earphones-service
  labels:
    app: earphones
spec:
  type: ClusterIP
  selector:
    app: earphones
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
