apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 754309742701.dkr.ecr.us-east-1.amazonaws.com/shopping-site-main:0ec03a836cf61103561ec70baad8f4265fbe2a6e
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
  labels:
    app: main-frontend
spec:
  type: ClusterIP
  selector:
    app: main-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
